import React, { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowDown, ArrowUpRight, ArrowRight, Menu, X, ChevronLeft, ChevronRight } from 'lucide-react';
import { services, labIdeas, projects, testimonials, lifestyle } from './content';
import './styles.css';

const socials = [{label:'Instagram', href:'https://www.instagram.com/_william_jefferson/'},{label:'TikTok',href:'https://www.tiktok.com/@play_bobby'},{label:'WhatsApp',href:'https://wa.me/2348074449909'},{label:'Email',href:'mailto:william@jollypadi.com'}];
function Header(){
  const [open,setOpen]=useState(false);
  useEffect(()=>{document.body.classList.toggle('menu-open',open); const onKeyDown=(event)=>{if(event.key==='Escape')setOpen(false)}; window.addEventListener('keydown',onKeyDown); return ()=>{document.body.classList.remove('menu-open');window.removeEventListener('keydown',onKeyDown)}},[open]);
  return <header className="header"><a className="wordmark" href="#top" aria-label="Jolly Padi home">JOLLY PADI<span>®</span></a><nav id="primary-navigation" className={open?'nav open':'nav'} aria-label="Main navigation">{[['Work','#work'],['Services','#services'],['Lab','#lab'],['About','#about'],['Contact','#contact']].map(([name,url])=><a key={name} href={url} onClick={()=>setOpen(false)}>{name}</a>)}<a className="nav-cta" href="#contact" onClick={()=>setOpen(false)}>LET’S TALK <ArrowUpRight size={14}/></a></nav><button className="menu-toggle" onClick={()=>setOpen(!open)} aria-label={open?'Close navigation':'Open navigation'} aria-expanded={open} aria-controls="primary-navigation">{open?<X/>:<Menu/>}</button></header>
}
function SectionLabel({children}){return <div className="section-label"><span className="label-dot"/>{children}</div>}
function Reveal({children,className=''}){return <div className={`reveal ${className}`}>{children}</div>}
function Hero(){return <section id="top" className="hero"><div className="hero-image" role="img" aria-label="Jolly Padi creative director overlooking Lagos at blue hour"/><div className="hero-grain"/><div className="hero-copy"><SectionLabel>JOLLY PADI® <i>/</i> CREATIVE MARKETING STUDIO</SectionLabel><h1>WE MAKE<br/>BRANDS<br/><em>HARD TO IGNORE.</em></h1><p>Creative strategy, content &amp; advertising for brands that want more than likes.</p><div className="hero-actions"><a className="button button-gold" href="#contact">START A PROJECT <ArrowUpRight size={15}/></a><a className="text-link" href="#work">EXPLORE OUR WORK <ArrowDown size={14}/></a></div></div><div className="hero-side-note"><span>01 / 04</span><span>LAGOS, NIGERIA</span></div><a className="scroll-cue" href="#idea" aria-label="Scroll to introduction"><span>SCROLL TO EXPLORE</span><ArrowDown size={13}/></a></section>}
function Idea(){return <section id="idea" className="idea section-pad"><Reveal><SectionLabel>01 — THE IDEA</SectionLabel><div className="idea-grid"><h2>MARKETING<br/>SHOULD FEEL<br/><em>LIKE CULTURE.</em></h2><div className="idea-copy"><span className="idea-star">✳</span><p>People don’t wake up wanting to see another advertisement.</p><p>They want something interesting.</p><p>So we create marketing that earns attention before asking for it.</p><a href="#services" className="text-link">THE WAY WE WORK <ArrowDown size={14}/></a></div></div></Reveal></section>}
function Services(){const [active,setActive]=useState(-1);return <section id="services" className="services section-pad"><Reveal><div className="section-heading"><SectionLabel>02 — THE OFFER</SectionLabel><h2>WHAT WE <em>DO</em></h2></div><div className="service-list" onMouseLeave={()=>setActive(-1)}>{services.map((s,i)=><article className={`service-row ${active===i?'active':''} ${s.tone}`} key={s.n} onMouseEnter={()=>setActive(i)}><button className="service-trigger" onClick={()=>setActive(active===i?-1:i)} aria-expanded={active===i} aria-controls={`service-detail-${s.n}`}><span className="service-num">{s.n}</span><span className="service-name">{s.name}</span><span className="service-summary">{s.summary}</span><span className="service-icon"><ArrowUpRight size={18}/></span></button><div id={`service-detail-${s.n}`} className="service-detail" aria-hidden={active!==i}><div className="service-detail-inner"><p>GOOD ATTENTION, PUT TO WORK.</p><ul>{s.items.map(x=><li key={x}>{x}</li>)}</ul></div><span className="detail-asterisk">✳</span></div></article>)}</div></Reveal></section>}
function Lab(){return <section id="lab" className="lab section-pad"><Reveal><div className="lab-head"><div><SectionLabel>THE JOLLY PADI LAB</SectionLabel><h2>MARKETING IS EASIER<br/>WHEN YOU UNDERSTAND<br/><em>ATTENTION.</em></h2></div><div className="lab-intro"><p>Every week, we take a business and ask:</p><blockquote>“If this were our client, how would we market it?”</blockquote></div></div><div className="lab-grid">{labIdeas.map(x=><a key={x.mark} className={`lab-card ${x.color}`} href="#contact"><span className="lab-card-index">JP LAB <b>{x.mark}</b></span><span className="lab-art" aria-hidden="true"><i>{x.mark}</i><b>✳</b></span><span className="lab-card-type">{x.type}</span><span className="lab-card-title">{x.title}</span><span className="card-arrow"><ArrowUpRight size={16}/></span></a>)}</div><div className="lab-foot"><span>IDEAS IN PUBLIC. STRATEGY IN PRACTICE.</span><a className="text-link" href="#contact">SEE THE LAB <ArrowRight size={15}/></a></div></Reveal></section>}
function ProjectCard({project}){return <article className={`project ${project.theme}`}><div className="project-visual"><div className="project-photo-placeholder"><span>IMAGE PLACEHOLDER</span><b>{project.imageLabel}</b><small>REPLACE WITH {project.client} CAMPAIGN PHOTOGRAPHY</small></div><div className="project-mark">{project.theme==='hauslet'?'H.':project.theme==='velox'?'V /':'N°'}</div><span className="project-index">{project.number} / 03</span></div><div className="project-info"><div><span className="project-category">{project.category}</span><h3>{project.client}</h3></div><p>{project.statement}</p><a href="#contact" aria-label={`Discuss a project like ${project.client}`}><ArrowUpRight size={19}/></a></div></article>}
function Work(){return <section id="work" className="work section-pad"><Reveal><div className="work-head"><SectionLabel>SELECTED WORK</SectionLabel><h2>PEOPLE WHO<br/><em>TRUSTED US.</em></h2><span className="work-side">THOUGHTFUL WORK.<br/>REAL WORLD RESULTS.</span></div><div className="project-list">{projects.map(p=><ProjectCard key={p.client} project={p}/>)}</div></Reveal></section>}
function About(){return <section id="about" className="about section-pad"><Reveal><figure className="about-photo"><img className="founder-image" src="/assets/william-duru-alexis.jpg" alt="William Duru-Alexis, founder of Jolly Padi" loading="lazy" decoding="async"/><figcaption className="photo-caption">WILLIAM DURU-ALEXIS / LAGOS, NIGERIA</figcaption></figure><div className="about-copy"><SectionLabel>THE GUY BEHIND THE PADI</SectionLabel><h2>I’M<br/><em>WILLIAM.</em></h2><p>I like good ideas, good business and figuring out why people do what they do online.</p><p>Jolly Padi started from that obsession.</p><p>How do you take an idea, put it in front of the right people and make them care?</p><div className="founder-signoff"><span>William Duru-Alexis</span><small>FOUNDER / CREATIVE STRATEGIST</small></div></div></Reveal></section>}
function Lifestyle(){return <section className="lifestyle section-pad"><Reveal><div className="life-top"><SectionLabel>OUTSIDE THE OFFICE</SectionLabel><p>THE BEST IDEAS DON’T ALL HAPPEN AT A DESK.</p></div><h2>LIFE IS PART<br/><em>OF THE BRAND.</em></h2><div className="life-gallery"><div className="life-feature"><span className="life-label">LIFE / LAGOS, NIGERIA</span><div className="feature-art"><span>JP®</span><i>✳</i></div><small>IMAGE PLACEHOLDER — LIFESTYLE EDITORIAL</small></div><div className="life-stack"><div className="life-tile tile-warm"><span>BUSINESS</span><b>THE<br/>WORK<br/>IN PROGRESS.</b><small>CONTENT PLACEHOLDER</small></div><div className="life-tile tile-pink"><span>STYLE / CULTURE</span><b>MAKE<br/>ROOM FOR<br/>GOOD TASTE.</b><small>CONTENT PLACEHOLDER</small></div></div></div><div className="life-tags">{lifestyle.map((x,i)=><span key={x}><b>0{i+1}</b>{x}</span>)}</div><div className="life-bottom"><span>JOLLY PADI, IN REAL LIFE.</span><a href="https://www.instagram.com/_william_jefferson/" className="text-link">FOLLOW ALONG <ArrowUpRight size={14}/></a></div></Reveal></section>}
function Testimonials(){const [index,setIndex]=useState(0);const t=testimonials[index];return <section className="testimonials section-pad"><Reveal><div className="testimonial-head"><SectionLabel>THEY SAID IT BETTER.</SectionLabel><span>NOTES FROM GOOD COMPANY</span></div><div className="testimonial-content" aria-live="polite"><span className="quote-mark">“</span><blockquote>{t.quote}</blockquote><div className="testimonial-meta"><span>{t.name}</span><span>{t.role}</span></div></div><div className="slider-controls"><span>0{index+1} <i>/</i> 0{testimonials.length}</span><button aria-label="Previous testimonial" onClick={()=>setIndex((index+testimonials.length-1)%testimonials.length)}><ChevronLeft/></button><button aria-label="Next testimonial" onClick={()=>setIndex((index+1)%testimonials.length)}><ChevronRight/></button></div></Reveal></section>}
function Contact(){return <section id="contact" className="contact section-pad"><Reveal><SectionLabel>READY?</SectionLabel><h2>LET’S MAKE<br/>SOMETHING<br/><em>PEOPLE REMEMBER.</em></h2><a className="button button-gold contact-button" href="mailto:william@jollypadi.com">START A PROJECT <ArrowUpRight size={16}/></a><div className="contact-links">{socials.map(s=><a key={s.label} href={s.href}>{s.label}<ArrowUpRight size={13}/></a>)}</div></Reveal></section>}
function Footer(){return <footer className="footer"><div className="footer-top"><a href="#top" className="wordmark">JOLLY PADI<span>®</span></a><p>Creative Marketing Studio<br/>Lagos, Nigeria</p><div className="footer-links">{socials.map(s=><a key={s.label} href={s.href}>{s.label}</a>)}</div><a className="back-top" href="#top">BACK TO TOP <ArrowUpRight size={13}/></a></div><div className="footer-bottom"><span>© 2026 JOLLY PADI. ALL RIGHTS RESERVED.</span><span>MADE WITH INTENT IN LAGOS <i>✳</i></span><a href="https://jollypadi.com">JOLLYPADI.COM</a></div></footer>}
function App(){useEffect(()=>{const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');observer.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(x=>observer.observe(x));return()=>observer.disconnect()},[]);return <><Header/><main><Hero/><Idea/><Services/><Lab/><Work/><About/><Lifestyle/><Testimonials/><Contact/></main><Footer/></>}

createRoot(document.getElementById('root')).render(<React.StrictMode><App/></React.StrictMode>);
